### ISSUE TITLE
soundin

### ISSUE THREAD

**Issue by rstvu** [csound/csound#1104]
soundin on windows produces distortion on output when updating skiptime via a parameter field variable

this appears to be a problem with several recent versions.

Need to know if this is just us or is there is a know issue here.

For teaching, this opcode is important and the fact that we cannot have it perform with reliable results presents difficulties.

diskin works perfectly.

With thanks for any insights.

Csound Version: 6_64 - Windows 64

**Comment by jpffitch** [comment]
What version?  I am not aware of a 6.64
A short example csd file would help

**Comment by stekyne** [comment]
I can test it out if you can supply an example

**Comment by rstvu** [comment]
Hi again:

Software version:  Csound6.12.0-Windows_x64-installer
Windows 7 64 bit with UA Apollo

The issue is distortion with soundin.  In fact this has been noted by us in previous versions as well.

For us, we get distortion with this simple effort.  There seems to be a problem with the opcode.  If we replace soundin with diskin, and make the necessary small modification, it works fine.  It would be helpful to have soundin working reliably for teaching purposes.  It is always possible that we are doing something wrong of course...

BTW: we are testing this within CSoundQt and cannot rule out other factors.  Both realtime output and also render to disk create the same effect.

It is very simple to test this.  Flute.was is a mono flute recording.  You could use another sound file.

Thanks so much for checking it out!
rst

Try the following:

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 1

instr 1
iskip = p4
a1	soundin	"flute.wav", iskip
out a1
endin

</CsInstruments>
<CsScore>

i1 0 1 2 
i1 + .  3
i1 + .  4
i1 + .  5
i1 + .  4
i1 + .  2

e

</CsScore>
</CsoundSynthesizer>

**Comment by rstvu** [comment]
The relatively recent change to source code with soundin, noted now using the diskin2 algo as we have read, may have introduced some kind of issue.

**Comment by jpffitch** [comment]
I tried with a sine wav input and the only problem was the discontinuity 
on each transition.  With a more complex sound did not get that.  Running 
on Linux though.

**Comment by rstvu** [comment]
Greetings,

This is a verified issue with complex audio - and on Windows - so, there is an issue for sure.  I have tried this on two modern systems under Windows 8 and Windows 7.  Both exhibit this issue.  It occurs, apparently, with pointer changes using skiptime the “discontinuity” results in distortion.  Hope this helps.

Sent from my iPad

RST
rst@aucourantrecords.com
www.aucourantrecords.com

**Comment by jpffitch** [comment]
I tried with a very simple version of flute.wav viz a straight line.  All 
looked OK.

soundin is just a front end to diskin2 anyway

==John ff

**Comment by rstvu** [comment]
Thank you for this check - does not explain the issues we are seeing - very strange and elusive, we wonder if anyone can replicate the issues?

Sent from my iPhone
Robert Scott Thompson, PhD

**Comment by jpffitch** [comment]
Could you post a link to the output you are getting? That might allow us 
to see the kind of distortion you are getting.

**Comment by rstvu** [comment]
Thanks for the effort to check.  We will continue with explorations here and see what we can discern.

Sent from my iPad

RST
rst@aucourantrecords.com
www.aucourantrecords.com

**Comment by rstvu** [comment]
Great idea - will do!

Sent from my iPhone
Robert Scott Thompson, PhD

**Comment by jpffitch** [comment]
Any progress n posting an example audio?

**Comment by rstvu** [comment]
Hi John, 

I will try to get to this tomorrow.  I will also do another test as I prepare that so that you have a better idea of what I have experience.

Thanks for the prompt – I would have been further delayed without it.

Best wishes,

Robert

**Comment by jpffitch** [comment]
We still have not got a distorted example and all our tests are OK.  Please can we have an example of the output and input?

**Comment by rstvu** [comment]
Hi John,

It seems that it is an issue with the sound file header and bit depth.  The subject file was 32-bit floating point, and the flag setting was 4 (16 bit).  The strange thing is that this setting will allow the file to play normally fine, but without changing the read pointer start time.  If that parameter is changed then distortion results.  I have told students to make a careful note of the bit depth of the source sounds and to make sure that the flag setting is correct for the given file.  This should solve it for them.  Thanks for your interest. (BTW: this issues is not found in the diskin opcode at all – it works as expected.)

All best,

Robert

**Comment by jpffitch** [comment]
I still cannot get any distortion.  I tried 64 bit PCM input and 32 bit 
floats with the same result.

**Comment by rstvu** [comment]
That makes the issue more complex, obviously.  I will see what I can do to get an input/output sample for you.  Will try to replicate the issue...

Sent from my iPad

RST
rst@aucourantrecords.com
www.aucourantrecords.com

**Comment by jpffitch** [comment]
I will close this issue at the end of the month if there us no more information.  So far it has not been reproduced by any developer.

**Comment by rstvu** [comment]
Thanks John!
I think it was an issue with the sound file encoding itself.

Sent from my iPad

RST
rst@aucourantrecords.com
www.aucourantrecords.com
