### ISSUE TITLE
no output from harmon* opcodes in csound 6.04

### ISSUE THREAD

**Issue by fsilvain** [csound/csound#431]
Using the examples from the Canonical Csound Reference Manual the harmon family of opcodes produces no audible signal.
Csound version: 6.04
Linux distro/kernel: Debian Squeeze with self-built vanilla kernel 3.9.0-rc6
The existence of the issue has been verified by another member of the Csound mailinglist.

**Comment by jpffitch** [comment]
Please can you direct me to an example?  I tried harmon3.csd and there is audio; is it the wrong audio?

**Comment by kunstmusik** [comment]
Yes, the audio should play, but you don't get the harmonizing effect.  I
rendered the harmon3.csd example with Csound 5 and placed it at:

http://kunstmusik.com/harmon3.wav

You should be able to hear the effect more pronounced on the 2nd and 3rd
iterations of the wave file.

**Comment by jpffitch** [comment]
Initialisation is sensative so we can share code between harmin2,3 and 4.  Unfortunately the order of arguments is  problematic and I think I got the logic wrong.  Will need to think about it.

Technically the code is the same but the additional frequencies disrupt the layout.

**Comment by jpffitch** [comment]
Fixed in git. it wa a side effect of the sample-accurate code which was not right.

**Comment by kunstmusik** [comment]
Works here now, but there is a lot of information being printed to the screen.  (Seems like leftover debugging code?)

**Comment by jpffitch** [comment]
Removed tracing -- apologies; too excited to have a fix!

**Comment by kunstmusik** [comment]
Thanks, the messages are now gone.  However, I think that another fix is
necssary: harmon3.csd works well, but harmon.csd is still not working
correctly. I think when I looked the other day, harmon used different code
than harmon3? I'm not positive though.

**Comment by jpffitch** [comment]
harmon is totally different code.  Will take a look.

**Comment by jpffitch** [comment]
Fixed/[atched.  Still anoddity but results identical
