### ISSUE TITLE
Macros consisting of digits only can be defined but not undefined

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#654]
For example, running

```csound
#define 123 #hello, world#
prints "$123\n"
#undef 123
```

results in this output:

```
123

macro exit undefined
Undefining undefined macrocannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
#
```

Commenting out `#undef 123` lets Csound run the orchestra.

**Comment by jpffitch** [comment]
Macro names as all numbers is a mistake.  My version requires an 
initial letter.  I will investigate the undef issue but it does not appen 
for me(!)

**Comment by jpffitch** [comment]
According to the manual "The name of the macro must begin with a letter and ..." wic ewas not property policed -- is now

**Comment by nwhetsell** [comment]
After commit 0764125, running

```csound
#define MACRO #hello, world#
#undef MACRO
scoreline_i "e"
```

with

```
csound --nosound --orc Test.orc
```

fails, but running

```csound
#define MACRO #hello, world#
#undef MACRO(
scoreline_i "e"
```

(note the open parenthesis in the `#undef` directive) succeeds. In commit 0764125, the regex used to find a macro name in the preprocessor’s `umacro` state was changed from `IDENT` to `MACRO`, but [the `MACRO` regex ends with an open parenthesis](https://github.com/csound/csound/blob/0764125d55cacd37d6b9f6b3e1834c25c67a5c64/Engine/csound_pre.lex#L73). I think that regex should’ve remained `IDENT`.

**Comment by jpffitch** [comment]
Think I fixed this; in git now

**Comment by nwhetsell** [comment]
It seems that now macros consisting of digits only can be defined and undefined, but not used. Running

```csound
#define 123 #hello, world#
prints "$123\n"
#undef 123
scoreline_i "e"
```

results in

```
Csound version 6.07 (double samples) Jun 12 2016
libsndfile-1.0.26
orchname:  Test.orc
macro 123 undefined
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.07 (double samples) Jun 12 2016
graphics suppressed, ascii substituted
0dBFS level = 32768.0
$123
orch now loaded
audio buffered in 1024 sample-frame blocks
not writing to sound disk
SECTION 1:
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
```

I think the way to address this issue so that the preprocessor adheres more closely to [the description of `#define` in the manual](https://csound.github.io/docs/manual/define.html) is to change `IDENTN` to `IDENT` [here](https://github.com/csound/csound/blob/9f53f3c810e6c8d523fc79d0f8f51a46f08c3016/Engine/csound_pre.lex#L514) and [here](https://github.com/csound/csound/blob/9f53f3c810e6c8d523fc79d0f8f51a46f08c3016/Engine/csound_pre.lex#L528).

**Comment by jpffitch** [comment]
I get a error

orchname:  pre.orc
rtmidi: ALSA Raw MIDI module enabled
rtaudio: pulseaudio module enabled

error: syntax error, unexpected STRING_TOKEN  (token ""#define 123 #hello, 
world#
#line   1
prints "") from file pre.orc (1)
  line 0:
>>>prints " <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

Not idea but it is looking for a valid macro name

**Comment by nwhetsell** [comment]
> error: syntax error, unexpected STRING_TOKEN  **(token ""#define 123 #hello,
world#
#line   1
prints "")** from file pre.orc

The part that I made **bold** seems to indicate that Csound is finding a string token with a value of

```
"#define 123 #hello,
world#
#line   1
prints "
```

in pre.orc, which is odd.

**Comment by nwhetsell** [comment]
I’m not sure why this has been closed. Running

```csound
#define 123 #hello, world#
prints "$123\n"
#undef 123
scoreline_i "e"
```

still shows

```
macro 123 undefined
```

in the output of the Jun 18 2016 version of Csound, which means it’s still possible to define macros consisting of digits only.

Here’s a ZIP archive containing the orchestra file I’m using: https://github.com/csound/csound/files/321797/Test.orc.zip

**Comment by nwhetsell** [comment]
It looks like this was addressed in 3a155d5 and 6003dd7.

I should note that 3a155d5 added a [`MACRO` regex pattern](https://github.com/csound/csound/blob/3a155d562a2c66bef718e6b30bc6fdb08eced28f/Engine/csound_pre.lex#L74) that’s identical to the [`IDENT` pattern](https://github.com/csound/csound/blob/3a155d562a2c66bef718e6b30bc6fdb08eced28f/Engine/csound_pre.lex#L67), `#define` and `#undef` now use the `MACRO` pattern, and [`#ifdef` (and `#ifndef`) still use the `IDENT` pattern](https://github.com/csound/csound/blob/6003dd762a46f86094f663bc15a44e65a32b5e19/Engine/csound_pre.lex#L557). It seems like only one of `MACRO` or `IDENT` is needed; and `#define`, `#undef`, `#ifdef`, and `#ifndef` should use the same pattern.
